---
- name: Copy Nginx repo configuration
  template: src=/root/ansible/files/nginx/nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Enable Nginx repo
  shell: yum-config-manager --enable nginx-stable

- name: Install nginx
  yum: name=nginx state=latest

- name: Copy Nginx configuration
  copy:
    src: /root/ansible/files/nginx/default.conf 
    dest: /etc/nginx/conf.d/default.conf
    remote_src: no
  notify: restart nginx

- firewalld:
    zone: public
    service: http
    permanent: yes
    state: enabled
  notify: restart firewalld
