- name: Copy temp config
  copy:
    src: /root/apiato_ansible/files/nginx_working/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: Copy Nginx.conf
  copy:
    src: /root/apiato_ansible/files/tunes/nginx.conf
    dest: /etc/nginx/nginx.conf
    remote_src: no

- name: Copy static info
  copy:
    src: /root/apiato_ansible/files/nginx_working/index.html
    dest: /var/www/working/
    owner: root
    group: root
    force: yes

- name: Test nginx
  command: nginx -t

- name: Restart nginx
  systemd:
    name: nginx
    state: reloaded
    enabled: yes
