---
- name: db_server
  hosts: db_server
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false

  roles:
   - selinux
   - postgres_install
   - postgres_setting

- name: app_server
  hosts: app_server
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false

  pre_tasks:
  - name: Set ansible distribution major version
    set_fact:
      ansible_distribution_major_version: "7"

  roles:
    - selinux
    - epel
    - yum-utils
    - remi_repo
    - php_stable
    - nginx
    - php
    - redis
    - git
    - beanstalkd
    - apiato
