---
- name: db_server
  hosts: db_server
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false

  roles:
  - rollback_db

- name: app_server
  hosts: app_server
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false

  roles:
  - migrate
