---
- name: app_server
  hosts: app_server
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: false

  roles:
  - backup_apiato
  - nginx_working
  - apiato_update
  - nginx_comeback
