---
- name: Copy v9.0.0 archive to app server
  copy:
    src: /root/apiato-v9.0.0.zip
    dest: /root/apiato-v9.0.0.zip

- name: Install zip
  yum:
    name: ['unzip', 'zip']

- name: Change owner apiato dir
  file:
    path: /var/www/apiato
    state: directory
    owner: nginx
    group: nginx
    recurse: yes

- name: Unarchive
  unarchive:
    src: /root/apiato-v9.0.0.zip
    dest: /var/www/apiato
    remote_src: yes

- name: Copy apiato env file
  copy:
    src: /root/apiato_ansible/files/apiato/env
    dest: /var/www/apiato/
    force: yes
    owner: root
    group: root
  become: true

- name: Rename to .env
  command: cp /var/www/apiato/env /var/www/apiato/.env

- name: Change mode bootstrap
  file:
    path: /var/www/apiato/bootstrap
    owner: nginx
    group: nginx
    mode: '777'
    state: directory
    recurse: yes

- name: Change mode storage
  file:
    path: /var/www/apiato/storage
    owner: nginx
    group: nginx
    mode: '777'
    state: directory
    recurse: yes

- name: Run artisan key generate
  command: php /var/www/apiato/artisan key:generate

- name: Run artisan migrate
  command: php /var/www/apiato/artisan migrate

- name: Run artisan db seed
  command: php /var/www/apiato/artisan db:seed

- name: Run artisan permissions
  command: php /var/www/apiato/artisan apiato:permissions:toRole admin
