- name: Copy default.conf
  copy:
    src: /root/apiato_ansible/files/nginx/default.conf
    dest: /etc/nginx/conf.d/default.conf

- name: Copy Nginx.conf
  copy:
    src: /root/apiato_ansible/files/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    remote_src: no

- name: Copy php-fpm configuration
  copy:
    src: /root/apiato_ansible/files/tunes/www.conf
    dest: /etc/php-fpm.d/www.conf
    force: yes
    owner: root
    group: root
  become: true

- name: Test nginx conf
  command: nginx -t

- name: Restart nginx
  systemd:    
    name: nginx
    state: reloaded
    enabled: yes

- name: Restart php-fpm
  systemd:
    name: php-fpm
    state: reloaded
    enabled: yes
