---
- name: Enable remi
  command: yum-config-manager --enable remi

- name: Disable old php
  command: yum-config-manager --disable remi-php54

- name: Enable actual php
  command: yum-config-manager --enable remi-php73
