---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted
    daemon_reload: yes
