---
- name: Copy Nginx basic php configuration
  copy:
    src: /root/apiato_ansible/files/nginx/default.conf
    dest: /etc/nginx/conf.d/default.conf
    remote_src: no

- name: Test nginx conf
  command: nginx -t
  register: result
  ignore_errors: True

- name: Rollback to static nginx
  include: "/root/apiato_ansible/roles/nginx_working/tasks/main.yml"
  when: result is failed

- name: Restart nginx
  systemd:
    name: nginx
    state: reloaded
