---
- name: Copy archive to app server
  copy:
    src: /root/apiato-v9.0.4.zip
    dest: /root/apiato-v9.0.4.zip

- name: Create dir for unarchive
  file:
    path: /var/www/apiato-v9.0.4
    state: directory
    owner: root
    group: root

- name: Unarchive
  unarchive:
    src: /root/apiato-v9.0.4.zip
    dest: /var/www/apiato-v9.0.4
    remote_src: yes

- name: Synchronization
  command: rsync /var/www/apiato-v9.0.4/ /var/www/apiato

- name: Run artisan migrate
  command: php /var/www/apiato/artisan migrate
